### ISSUE TITLE
Chapter 1 and 2 comments

### ISSUE THREAD

**Issue by taylorjwright** [RohanAlexander/telling_stories#21]
Loving the book so far, I'm currently making my way through chapter 3 and will continue posting any comments I have after I finish the chapters. Sorry if any comments I make now are addressed later on (and some of these are kind of pedantic, so apologies for that as well)!

# Chapter 1
- Exercise 6 refers to Crawford (2021) but it was not among the required material to start the chapter. Is that intentional?

# Chapter 2
- I really enjoyed the readings, particularly Chambliss. I think there's an opportunity to integrate the Hao reading a little more, either in the text itself or through the exercises. Specifically, asking or demonstrating the correspondence between the workflow steps and the stages at which bias can enter that Hao discusses and even extending this so that readers know this isn't a problem isolated to AI (as well as perhaps linking back to issues raised in the Kennedy reading from the previous chapter)
- In chapter 1 (and in the "Key concepts and skills" part of chapter 2 as well as section 2.1) you refer to the last step in the workflow as "share" but in chapter 2 it is "communicate", not sure if it makes sense to use the same language throughout for consistency and reinforcement? (because "communicate" is also referred to as  the most important of the key elements below the iceberg in the figure 1.1, it might cause confusion about what are the elements of the workflow and what are the elements underlying the workflow).
- The text mentions installing `janitor`and `tidyverse` but not `httr` (though the code chunks do include it of course) and `httr` isn't present in the Fig 2.4 screenshot.
- In sections 2.2.3 you motivate using `clean_names()` as removing spaces in variable names, but it doesn't appear that there are spaces in those names?
- I'm not sure if conceptually it's against the system you're presenting but I was thinking that it might be helpful (and in line with some of the readings about interrogating the data) to include (maybe in the planning step, or maybe as the first part of the acquire step and if the data you planned for are not available it's back to the drawing board?) examining the codebook of reference materials about the data? I'm not sure where you situate this feasibility check in your research process.
- In section 2.3.2 you load both the `tidyverse` and `tidyr`, is there a reason for that?
- In section 2.3.2 there is a comment "# Draw 552 times from the Poisson distribution", I'm not sure that still applies to the code chunk (could just be misreading)?
- In section 2.4.2 you mention the possibility that code needs to be rewritten when packages are updated, it might be worth mentioned that there are tools aimed at loading particular versions to help reproducibility. I had a quick look ahead and it looks like you cover `renv` so you could just say "which we'll be covering in more detail a few chapters from now".

**Comment by RohanAlexander** [comment]
Thank you very much for going through these chapters @taylorjwright and for these comments.

> Loving the book so far, I'm currently making my way through chapter 3 and will continue posting any comments I have after I finish the chapters. Sorry if any comments I make now are addressed later on (and some of these are kind of pedantic, so apologies for that as well)!
> 
> # Chapter 1
> * Exercise 6 refers to Crawford (2021) but it was not among the required material to start the chapter. Is that intentional?

Have updated the question to specify that the answer is in the chapter, and students don't need to necessarily find that reading.

> # Chapter 2
> * I really enjoyed the readings, particularly Chambliss. I think there's an opportunity to integrate the Hao reading a little more, either in the text itself or through the exercises. Specifically, asking or demonstrating the correspondence between the workflow steps and the stages at which bias can enter that Hao discusses and even extending this so that readers know this isn't a problem isolated to AI (as well as perhaps linking back to issues raised in the Kennedy reading from the previous chapter)

I love Chambliss - just the way that he writes is incredible.

With regard to Hao - that's an excellent idea. I've added it to the exercises.

> * In chapter 1 (and in the "Key concepts and skills" part of chapter 2 as well as section 2.1) you refer to the last step in the workflow as "share" but in chapter 2 it is "communicate", not sure if it makes sense to use the same language throughout for consistency and reinforcement? (because "communicate" is also referred to as  the most important of the key elements below the iceberg in the figure 1.1, it might cause confusion about what are the elements of the workflow and what are the elements underlying the workflow).

Thank you for noticing this. For the 5-step workflow, it should be "share". I've updated Ch 2 sub-headings.

> * The text mentions installing `janitor`and `tidyverse` but not `httr` (though the code chunks do include it of course) and `httr` isn't present in the Fig 2.4 screenshot.

I don't think that `httr` is needed here. I've removed it for now, and could add it back later if needed.

> * In sections 2.2.3 you motivate using `clean_names()` as removing spaces in variable names, but it doesn't appear that there are spaces in those names?

Good point. Have updated.

> * I'm not sure if conceptually it's against the system you're presenting but I was thinking that it might be helpful (and in line with some of the readings about interrogating the data) to include (maybe in the planning step, or maybe as the first part of the acquire step and if the data you planned for are not available it's back to the drawing board?) examining the codebook of reference materials about the data? I'm not sure where you situate this feasibility check in your research process.

Great point. Have added.

> * In section 2.3.2 you load both the `tidyverse` and `tidyr`, is there a reason for that?

Thanks for noticing this. Have updated.

> * In section 2.3.2 there is a comment "# Draw 552 times from the Poisson distribution", I'm not sure that still applies to the code chunk (could just be misreading)?

Have updated.

> * In section 2.4.2 you mention the possibility that code needs to be rewritten when packages are updated, it might be worth mentioned that there are tools aimed at loading particular versions to help reproducibility. I had a quick look ahead and it looks like you cover `renv` so you could just say "which we'll be covering in more detail a few chapters from now".

Great idea. Have added.
