### ISSUE TITLE
Ryan's chapter 5 review

### ISSUE THREAD

**Issue by ryancbriggs** [RohanAlexander/telling_stories#29]
My most general comment is that there is a lot of good advice packed into this chapter. kudos.

My most general criticism is that the chapter has a kind of "list" feel to it. If you're thinking it's sort of a reference, where someone thinks "damn, I'm stuck, how do I write an introduction? oh yeah! I'll check that Alexander book" then you're good. If you imagine someone reading it top to bottom then it's kind of boring and has this "sequential list of things" vibe. I'm not sure that's fixable, and I'm not sure its a problem, but I did feel it and it didn't feel great.

**Comments**
- 5.2: I think most people agree with the idea that "the critical task is to get to a first draft as quickly as possible. Until that complete first draft exists, it is useful to try to not to delete, or even revise, anything that was written, regardless of how bad it may seem. Just write." For what it is worth, I don't do this. I usually think about an idea in the form of a paper for a long time (weeks) after I get results and before I write much besides random notes. Then when I sit down I usually write something like a good second to third draft in a few days. I'm not saying you should soften or change the advice, but it feels weird to read advice that sounds right to me but is also wildly different from what actually do.
- 5.2: Something you don't mention but might be useful: Sometimes it is painful to cut paragraphs that seem good or have a good idea but don't belong in the paper. It can really ease the pain (and so allow for more and faster cutting) if you have a temp document that just holds these paragraphs "for later." Usually you'll never dig into that text file, but putting stuff there rather than deleting is empowering. It avoids the thing where people undercut out of fear that they'll lose a good idea or phrase.
- 5.2: Strongly endorse the idea of printing out a later draft to edit
- 5.3.2: Very good advice that I got on building theory, that may be useful to your readers, is that one can start with some interesting thing and then ask "of what is this an instance?". Doing this immediately forces you to think theoretically. The reader moves from "I care about this conflict in this place" to "oh, this is an instance of civil wars". Then we can think more generally about the dynamics. If you want to incorporate this, it's attributable to James N. Rosenau: https://www.jstor.org/stable/44838096
- 5.4.2: I'm really not sure my abstract is that good. I might cut it. I like the other examples. Maybe it's just hard to read your own writing.
- 5.4.8: "we are interested in grammar and sentence structure that occurs in conversational language use ([S. King 2000, 118](https://tellingstorieswithdata.com/99-references.html#ref-stephenking)). The way to develop that comfort is by reading a lot and asking others to also read your work." I agree. Another useful way to check this is to read your writing back to yourself out loud. We listen a lot more than we read, and so we can often better detect odd sentences by how they sound than by how they read.
- the exercises are cool. I really like what you're doing with them. That said, is it really important to get someone to memorize how many words an abstract should be to within 50 words (q13)?

**Small edits**
- "The only way to get better at writing, is to write, ideally every day." should be "The only way to get better at writing is to write, ideally every day."
- "At that point we start to rewrite brutally and removing as many words as possible." I think this is overstated and grammatically odd. Perhaps change to something like: "At that point we start to rewrite. When doing so we aim to maximize clarity, often by removing unnecessary words."
- "We typically begin with some area of interest, and then develop research questions and data in an iterative way." should be "We typically begin with some area of interest and then develop research questions and data in an iterative way"
- "Effective papers are tightly written and well-organized, which makes the story flow and easy to follow" feels grammatically odd to me. Perhaps change to "Effective papers are tightly written and well-organized, which makes their story easy to follow and flow well."
- "Effective papers demonstrate understanding of their topic by confidently using relevant terms and techniques appropriately, and considering issues without being overly verbose." could be "Effective papers demonstrate understanding of their topic by appropriately using relevant terms and techniques, and considering issues carefully without being verbose."
- "Graphs, tables, and references are used to enhance both the story and its credibility." could be "Both the quality of your story and its credibility can be enhanced by graphs, tables, and references."
- add explanation of NMR first time it is used
- I worry that mentioning haruspicy is more showing off a GRE word than making a good joke (though it was a decent joke)
- "And so attacking a generational-defining question might be best broken up into smaller chunks." should probably be "And so a generation-defining question might be best broken up into chunks."
- "One way that some researchers are data-first, is that they develop a particular expertise in the data of some geographical or historical circumstance." should be "One way that some researchers are data-first is that they develop a particular expertise in the data of some geographical or historical circumstance."
- "A/A testing" is a funny typo

Good stuff! Glad I could offer a little help.
Ryan

**Comment by RohanAlexander** [comment]
> My most general comment is that there is a lot of good advice packed into this chapter. kudos.
> 
> My most general criticism is that the chapter has a kind of "list" feel to it. If you're thinking it's sort of a reference, where someone thinks "damn, I'm stuck, how do I write an introduction? oh yeah! I'll check that Alexander book" then you're good. If you imagine someone reading it top to bottom then it's kind of boring and has this "sequential list of things" vibe. I'm not sure that's fixable, and I'm not sure its a problem, but I did feel it and it didn't feel great.
> 

Have added a sentence noting this at the start. Maybe forewarned is forearmed.

> **Comments**
> 
> * 5.2: I think most people agree with the idea that "the critical task is to get to a first draft as quickly as possible. Until that complete first draft exists, it is useful to try to not to delete, or even revise, anything that was written, regardless of how bad it may seem. Just write." For what it is worth, I don't do this. I usually think about an idea in the form of a paper for a long time (weeks) after I get results and before I write much besides random notes. Then when I sit down I usually write something like a good second to third draft in a few days. I'm not saying you should soften or change the advice, but it feels weird to read advice that sounds right to me but is also wildly different from what actually do.

Good point. Have added a footnote that clarifies this is directed at students, and will change with experience

> * 5.2: Something you don't mention but might be useful: Sometimes it is painful to cut paragraphs that seem good or have a good idea but don't belong in the paper. It can really ease the pain (and so allow for more and faster cutting) if you have a temp document that just holds these paragraphs "for later." Usually you'll never dig into that text file, but putting stuff there rather than deleting is empowering. It avoids the thing where people undercut out of fear that they'll lose a good idea or phrase.

This is an excellent point, and something that I also do, but didn't think about. Thank you. Have added.

> * 5.2: Strongly endorse the idea of printing out a later draft to edit

Proof that we're (roughly) the same age. The grad students make fun of me for doing this :(

> * 5.3.2: Very good advice that I got on building theory, that may be useful to your readers, is that one can start with some interesting thing and then ask "of what is this an instance?". Doing this immediately forces you to think theoretically. The reader moves from "I care about this conflict in this place" to "oh, this is an instance of civil wars". Then we can think more generally about the dynamics. If you want to incorporate this, it's attributable to James N. Rosenau: https://www.jstor.org/stable/44838096

Wow this is great. Thank you. Added.

> * 5.4.2: I'm really not sure my abstract is that good. I might cut it. I like the other examples. Maybe it's just hard to read your own writing.

I thought it was great. Will keep for now if that's okay.

> * 5.4.8: "we are interested in grammar and sentence structure that occurs in conversational language use ([S. King 2000, 118](https://tellingstorieswithdata.com/99-references.html#ref-stephenking)). The way to develop that comfort is by reading a lot and asking others to also read your work." I agree. Another useful way to check this is to read your writing back to yourself out loud. We listen a lot more than we read, and so we can often better detect odd sentences by how they sound than by how they read.

Great idea. Have added.

> * the exercises are cool. I really like what you're doing with them. That said, is it really important to get someone to memorize how many words an abstract should be to within 50 words (q13)?

Have removed.

> 
> **Small edits**
> 
> * "The only way to get better at writing, is to write, ideally every day." should be "The only way to get better at writing is to write, ideally every day."

Have changed.

> * "At that point we start to rewrite brutally and removing as many words as possible." I think this is overstated and grammatically odd. Perhaps change to something like: "At that point we start to rewrite. When doing so we aim to maximize clarity, often by removing unnecessary words."

Have changed.

> * "We typically begin with some area of interest, and then develop research questions and data in an iterative way." should be "We typically begin with some area of interest and then develop research questions and data in an iterative way"

Have changed.

> * "Effective papers are tightly written and well-organized, which makes the story flow and easy to follow" feels grammatically odd to me. Perhaps change to "Effective papers are tightly written and well-organized, which makes their story easy to follow and flow well."

You're right. Grammatically odd. Have changed.

> * "Effective papers demonstrate understanding of their topic by confidently using relevant terms and techniques appropriately, and considering issues without being overly verbose." could be "Effective papers demonstrate understanding of their topic by appropriately using relevant terms and techniques, and considering issues carefully without being verbose."

Have changed.

> * "Graphs, tables, and references are used to enhance both the story and its credibility." could be "Both the quality of your story and its credibility can be enhanced by graphs, tables, and references."

That's way better. Thank you.

> * add explanation of NMR first time it is used

Added a pointer to earlier in the book where it was introduced.

> * I worry that mentioning haruspicy is more showing off a GRE word than making a good joke (though it was a decent joke)

Sadly removed the GRE word (but kept the joke). 

> * "And so attacking a generational-defining question might be best broken up into smaller chunks." should probably be "And so a generation-defining question might be best broken up into chunks."

Have changed. 

> * "One way that some researchers are data-first, is that they develop a particular expertise in the data of some geographical or historical circumstance." should be "One way that some researchers are data-first is that they develop a particular expertise in the data of some geographical or historical circumstance."

Have changed.

> * "A/A testing" is a funny typo

Have added context.

> Good stuff! Glad I could offer a little help. Ryan

Thank you very much for reading this.
