### ISSUE TITLE
Arrow R Cookbook citation

### ISSUE THREAD

**Issue by thisisnic** [RohanAlexander/telling_stories#80]
Thanks for citing the Arrow R Cookbook! 😍

We didn't have any citation guidelines before, but I've written some now to acknowledge that it wasn't just me that did all the work. Would you mind adding Stephanie Hazlitt to the citation?

The PR giving guidance on how to cite hasn't yet been merged, but for reference, is here: https://github.com/apache/arrow-cookbook/pull/306

**Comment by RohanAlexander** [comment]
Thank you very much for taking the time to look at this Nic. I've updated my bibtex and the change will go live next time I build it.
