### ISSUE TITLE
Toronto shelter occupancy data

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [RohanAlexander/telling_stories#84]
The code that fetches the data for the Toronto shelter occupancy only returns dates from January to August

```
library(opendatatoronto)
library(tidyverse)

data <- list_package_resources("21c83b32-d5a8-4106-a54f-010dbe49f6f2") %>%
  filter(name == "daily-shelter-overnight-service-occupancy-capacity-2021") %>%
  get_resource()

months <- month(data$OCCUPANCY_DATE)

unique(months)
```
Output:
```
[1] 1 2 3 4 5 6 7 8
```

Table 2.2 on page 36 shows averages for all 12 months.

**Comment by RohanAlexander** [comment]
Thanks for this. You're right. They've updated the dataset. I'll need to change the code in a few places. Will try to do it tomorrow.

**Comment by RohanAlexander** [comment]
I've updated the code. Thanks again @tibbles-and-tribbles . Can you send me an email with your name so that I can add you to the acknowledgements?

Rohan

**Comment by tibbles-and-tribbles** [comment]
You’re welcome. 

Andrew Black
***@***.***
