### ISSUE TITLE
Chapter 5, figure 5.21 - boxplots

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [RohanAlexander/telling_stories#86]
The plotting code that constructs Figure 5.21 contains the line `scale_color_brewer(palette="Set1")`, which could be removed because nothing is being colored in the resulting boxplots.

Also, the caption for Figure 5.21 should read "Distribution of inflation data..." not "Distribution of unemployment data..."

Andrew Black

**Comment by RohanAlexander** [comment]
You're right! Thank you very much for finding these mistakes. 
Will fix in the online version.
