### ISSUE TITLE
File 1996_Tanzania_DHS.pdf not available

### ISSUE THREAD

**Issue by alfonsoACE** [RohanAlexander/telling_stories#88]
Hello,
I am learning Quarto by reproducing your book "Telling Stories". While building the book there is an error in `chapter 09-clean_and_prepare.qmd`, because it doesn't find a PDF file that is supposed to read. The file is `1996_Tanzania_DHS.pdf`. This happens between lines 1275-1280.

**Comment by RohanAlexander** [comment]
Hi @alfonsoACE,

Thank you for your issue.

I think that the public code before that downloads the PDF:
`download.file(
  url = "https://dhsprogram.com/pubs/pdf/FR83/FR83.pdf",
  destfile = "1996_Tanzania_DHS.pdf",
  mode = "wb"
)`

And so for students who are running through the code, it's fine.

As you say, if someone is trying to re-build the book, then they need to have that file already there, and I'm not sure that there's code that does that.

I'll add something hidden, and doesn't execute, in the next push.

Thank you!

Rohan
