### ISSUE TITLE
2020 Cooperative Election Study - Chapter 13

### ISSUE THREAD

**Issue by tidyeval** [RohanAlexander/telling_stories#89]
2020 Cooperative Election Study  not available (Server returns 503).
Might be good to store all the data used in the book (which is fantastic and I enjoy reading!!) in a data folder in the repo.
Thanks!

**Comment by RohanAlexander** [comment]
Thank very much for creating an issue.

Are you referring to the link circled in the image? If so, that's working for me now. Maybe it was just something temporary with their server.

<img width="1563" alt="Screenshot 2023-10-11 at 2 59 12 PM" src="https://github.com/RohanAlexander/telling_stories/assets/5662323/fb7bd72a-6c22-4d4b-b6fb-39a273677860">

**Comment by tidyeval** [comment]
Perfect, thanks for taking the time!
