### ISSUE TITLE
[Chapter 6 Table 11.2] Typo when describing Florida's numbers

### ISSUE THREAD

**Issue by david-jankoski** [RohanAlexander/telling_stories#91]
The table [here](https://tellingstorieswithdata.com/11-eda.html#tbl-imputationoptions) says that Florida has population of 11,197 according to the Multiple Imputation method, whereas the text here says a different number 5,814 which i believe is a typo.
https://github.com/RohanAlexander/telling_stories/blob/1fe8867c3eda40344b2bc8f6e3da4162946f6df7/11-eda.qmd#L303

It's a very simple change which if you agree and approve - I can make a fix PR and submit it.  

Thank you for writing and making this book freely available. I enjoyed exploring many of the interesting references you leave throughout like the one on Tukey's The Future of Data Analysis.

**Comment by RohanAlexander** [comment]
Thank you very much for this. Will update the website and acknowledge you.
