### ISSUE TITLE
[Chapter 6 Figure 11.10] Typo when describing prices

### ISSUE THREAD

**Issue by david-jankoski** [RohanAlexander/telling_stories#92]
The code used to produce the graph [here](https://tellingstorieswithdata.com/11-eda.html#fig-airbnbpricesfirst-2) on London AirBnb prices histogram says `filter > 1000` while the explanation below says the opposite.  

https://github.com/RohanAlexander/telling_stories/blob/1fe8867c3eda40344b2bc8f6e3da4162946f6df7/11-eda.qmd#L1031  

I believe it's a smol typo and similarly to [this one](https://github.com/RohanAlexander/telling_stories/issues/91) - if you believe it's so and agree/approve - I'm happy to submit a PR to fix this.  
Again - thank you for writing and offering freely the book.

**Comment by RohanAlexander** [comment]
Thank you very much for letting me know. I will fix and acknowledge you!
