### ISSUE TITLE
References - Barrett - broken link

### ISSUE THREAD

**Issue by clayford** [RohanAlexander/telling_stories#93]
The link for the following reference is broken:

Barrett, Malcolm. 2021a. Data Science as an Atomic Habit. https://malco.io/2021/01/04/data-science-as-an-atomic-habit/. 

It appears to be accessible though archive.org:

https://web.archive.org/web/20230201092111/https://malco.io/2021/01/04/data-science-as-an-atomic-habit/

**Comment by RohanAlexander** [comment]
That blog link has jumped around a bit, so Thank you for the Web Archive link! Very useful.
I'll update.
