### ISSUE TITLE
Link to free online version of book dead

### ISSUE THREAD

**Issue by paulauvirage** [RohanAlexander/telling_stories#96]
Hello the link to the free online version of the  book leads to a 404 page. Is this still available elsewhere.

Many thanks

**Comment by RohanAlexander** [comment]
Thanks for your issue. I messed up a minor commit today and haven’t fixed it yet. Should be able to roll back tomorrow.

Rohan

**Comment by RohanAlexander** [comment]
Working again for me now @paulauvirage. How about you? Thanks for your note yesterday.

**Comment by paulauvirage** [comment]
Yes it works now, thanks very much.

Superb book by the way, I'm using it and McElreath as the basis for developing a postgrad stats course here in Sierra Leone for 2024.
